  # A conda environment with packages necessary for event types study
name: event_types
channels:
  - default
dependencies:
  - python
  - pip
  - ipython
  - jupyter
  - numpy
  - numpydoc
  - matplotlib
  - pytables
  - pandas
  - astropy
  - scikit-learn
  - seaborn
  - conda-forge::uproot
  - pre-commit
  - pyflakes
